### ISSUE TITLE
Add code to plot SNVs vs. time between samples to vignette

### ISSUE THREAD

**Issue by sthiede** [Snitkin-Lab-Umich/regentrans#18]
scatter plot with time on the x axis and SNV distance on the y axis -- for isolates under a certain SNV threshold indicative of recent transmission (and maybe overall, as well?)

**Comment by zenalapp** [comment]
We should add this to the vignette, I think.

**Comment by zenalapp** [comment]
I think this might not be worth including because of our dataset.

**Comment by zenalapp** [comment]
Done
